// Generated by IcedCoffeeScript 1.2.0i
(function() {
  var app, express, gm, _;

  express = require('express');

  app = express();

  app.use(express["static"](__dirname + '/public'));

  _ = require('underscore');

  gm = require('googlemaps');

  app.get('/proxy/reverseGeocode', function(req, res) {
    return gm.reverseGeocode(req.param('latlng'), function(err, response) {
      var components, postal_code, result, route, street_number;
      components = _.map(response.results[0].address_components, function(component) {
        var part, value;
        part = component.types[0];
        value = component.long_name;
        return {
          part: part,
          value: value
        };
      });
      postal_code = _.find(components, function(c) {
        return c.part === 'postal_code';
      }).value;
      route = _.find(components, function(c) {
        return c.part === 'route';
      }).value;
      street_number = _.find(components, function(c) {
        return c.part === 'street_number';
      }).value;
      result = [postal_code, route, street_number].join(' ');
      console.log('[GET]', req.url, '->', result);
      return res.send(result);
    });
  });

  app.listen(8080);

  console.log('server listening at port 8080');

}).call(this);
