// Generated by IcedCoffeeScript 1.2.0i
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(express["static"](__dirname + '/public'));

  app.listen(8080);

}).call(this);
